title: "Pipeline report"
subtitle: "Taxonomic profiling of eukaryote species from food and seed materials."
custom_logo: "pipelinelogo.png"
custom_logo_title: "marchoeppner/eutaxpro"
custom_logo_url: "http://www.github.com/marchoeppner/eutaxpro"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt
    - .pass

report_comment: >
    This report has been generated automatically by marchoeppner/eutaxpro.
    For help interpreting the outputs, please see: https://github.com/marchoeppner/eutaxpro
report_header_info:
    - Contact E-mail: "mphoeppner@gmail.com"
    - Application Type: "Taxonomic profiling from amplicons"

top_modules:
    - 'general_stats'

report_section_order:
    software_versions:
        order: -1001
